### ISSUE TITLE
Cannot call method 'map' of undefined

### ISSUE THREAD

**Issue by sptmru** [nickpisacane/mongooseToCsv#1]
Hi,

Received this error when trying to use the module:
TypeError: Cannot call method 'map' of undefined
    at MongooseToCsv._createHeaders (node_modules/mongoose-to-csv/index.js:199:17)

**Comment by nickpisacane** [comment]
Hi supporteam,

I am currently in the process of making breaking changes to mongoose-to-csv. What i am doing is making it an actual "mongoose plugin" and going to be implementing my other project `Csv-Builder` under the hood. Csv-Builder covers a lot of the bugs in mongoose-to-csv and is not just for mongoose documents. The api is very similar, the major difference is that it is streams only. If you post a snippet I would be happy to show you how to implement it with Csv-Builder

**Comment by nickpisacane** [comment]
Ok I have pushed the new version, for npm versions pre 0.1.0 can be found on the `v0` branch. I am going to close this as the api has changed completely and the issue has hopefully been mitigated.
