### ISSUE TITLE
Comma vs | delimiters

### ISSUE THREAD

**Issue by bmetcalfe1** [nickpisacane/mongooseToCsv#2]
How can we seperate by " | " instead of " , " ?

Is it possible to choose the delimiter?

**Comment by nickpisacane** [comment]
Looks like you found the `delimiter` option. This needs to be documented. Thanks for opening the issue!

**Comment by nickpisacane** [comment]
Forgot that API section of README links to CsvBuilder, but [this](https://github.com/nickpisacane/mongooseToCsv/commit/535ea4a8aa9915f3196c808da5731d11e9fd0621)  adds another link to the repo.
