### ISSUE TITLE
Strategy for escaping commas?

### ISSUE THREAD

**Issue by joewagner** [nickpisacane/mongooseToCsv#3]
Thank you for managing this lib.  Do you have a strategy to setup escaping commas?  
For example:
foo, "baz, bar", derp

My only thought is to use a virtual that wraps values in double quotes while escaping double quotes contained in the value. I would potentially be doing this for every field.  Is that the best approach?

**Comment by steenhansen** [comment]
See https://www.npmjs.com/package/mongoose-to-csv-quotes for escaping commas
